#!/bin/bash

tf_config_exist=0
tf_current_dir=$(pwd)

if [ -f "tf_config" ]; then
    echo "File tf_config already exists."
    tf_config_exist=1
fi

if [ $tf_config_exist == 0 ]; then

    touch tf_config

    echo "#!/bin/bash" >> tf_config
    echo "" >> tf_config
    echo "# Absolute path to current directory" >> tf_config
    echo "export tf_path=$tf_current_dir" >> tf_config
    echo "" >> tf_config
    echo "# Add core path to PYTHONPATH variable" >> tf_config
    echo "export PYTHONPATH=\$tf_path/core:\$PYTHONPATH" >> tf_config
    echo "" >> tf_config
    echo "# Add core path to PATH variable" >> tf_config
    echo "export PATH=\$tf_path/core:\$PATH" >> tf_config
    echo "" >> tf_config
    echo "# Source tf_complete to setup autocomplete function in terminal line" >> tf_config
    echo "source \$tf_path/core/tf_complete" >> tf_config
    echo "" >> tf_config

fi
