#!/usr/bin/env bash

tf_complete(){
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    subcommands_1="-config -syn -impl -atpg -power -formal -ui_mode -update_run_dir -from_step -to_step -step -help"
    subcommands_ui_mode="interactive terminal"
    subcommands_update_run_dir="all cfg step_scripts input_data"

    COMPREPLY=( $(compgen -W "${subcommands_1}" -- ${cur}) )

    subcmd_1="${COMP_WORDS[COMP_CWORD-1]}"
    case "${subcmd_1}" in
    -config)
      COMPREPLY=($(compgen -df -- ${cur}))
      ;;
    -syn)
      COMPREPLY=( $(compgen -W "${subcommands_1}" -- ${cur}) )
      ;;
    -impl)
      COMPREPLY=( $(compgen -W "${subcommands_1}" -- ${cur}) )
      ;;
    -atpg)
      COMPREPLY=( $(compgen -W "${subcommands_1}" -- ${cur}) )
      ;;
    -power)
      COMPREPLY=( $(compgen -W "${subcommands_1}" -- ${cur}) )
      ;;
    -formal)
      COMPREPLY=( $(compgen -W "${subcommands_1}" -- ${cur}) )
      ;;
    -ui_mode)
      COMPREPLY=( $(compgen -W "${subcommands_ui_mode}" -- ${cur}) )
      ;;
    -update_run_dir)
      COMPREPLY=( $(compgen -W "${subcommands_update_run_dir}" -- ${cur}) )
      ;;
    -from_step)
      COMPREPLY=()
      ;;
    -to_step)
      COMPREPLY=()
      ;;
    -step)
      COMPREPLY=()
      ;;
    -help)
      COMPREPLY=( $(compgen -W "${subcommands_1}" -- ${cur}) )
      ;;
    cfg)
      COMPREPLY=( $(compgen -W "${subcommands_update_run_dir}" -- ${cur}) )
      ;;
    step_scripts)
      COMPREPLY=( $(compgen -W "${subcommands_update_run_dir}" -- ${cur}) )
      ;;
    input_data)
      COMPREPLY=( $(compgen -W "${subcommands_update_run_dir}" -- ${cur}) )
      ;;
    esac
}

complete -F tf_complete the_flow
